<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-21T11:30:32 IST" name="Suite" finished-at="2024-06-21T11:30:32 IST" duration-ms="87">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidation.loginErrorValidation()[pri:0, instance:Rahulshettyacedemy.Tests.ErrorValidation@1972e513]" name="loginErrorValidation" class="Rahulshettyacedemy.Tests.ErrorValidation"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2024-06-21T11:30:32 IST" name="Standalone Submit Order Test" finished-at="2024-06-21T11:30:32 IST" duration-ms="13">
    </test> <!-- Standalone Submit Order Test -->
    <test started-at="2024-06-21T11:30:32 IST" name="Error Validation" finished-at="2024-06-21T11:30:32 IST" duration-ms="87">
      <class name="Rahulshettyacedemy.Tests.ErrorValidation">
        <test-method signature="loginErrorValidation()[pri:0, instance:Rahulshettyacedemy.Tests.ErrorValidation@1972e513]" started-at="2024-06-21T11:30:32 IST" name="loginErrorValidation" finished-at="2024-06-21T11:30:32 IST" duration-ms="22" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "Rahulshettyacedemy.pageobjects.LandingPage.loginApplication(String, String)" because "this.landingPage" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "Rahulshettyacedemy.pageobjects.LandingPage.loginApplication(String, String)" because "this.landingPage" is null
at Rahulshettyacedemy.Tests.ErrorValidation.loginErrorValidation(ErrorValidation.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
      </class> <!-- Rahulshettyacedemy.Tests.ErrorValidation -->
    </test> <!-- Error Validation -->
  </suite> <!-- Suite -->
</testng-results>
